name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Lint
        run: yarn lint

      - name: Unit test
        run: yarn test:unit

      - name: End-to-end test
        uses: cypress-io/github-action@v2
        if: github.event_name == 'push'
        with:
          headless: true
          record: true
          start: yarn cy:setup
          wait-on: 'http://localhost:10003'
          install: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
